void LDfunc(Register r1, Register r2, Register r3, Immediate imm);
void STfunc(Register r1, Register r2, Register r3, Immediate imm);
void LIfunc(Register r1, Register r2, Register r3, Immediate imm);
void ADDfunc(Register r1, Register r2, Register r3, Immediate imm);
void SUBfunc(Register r1, Register r2, Register r3, Immediate imm);
void NEGfunc(Register r1, Register r2, Register r3, Immediate imm);
void MULfunc(Register r1, Register r2, Register r3, Immediate imm);
void MULFfunc(Register r1, Register r2, Register r3, Immediate imm);
void RECPfunc(Register r1, Register r2, Register r3, Immediate imm);
void TSTfunc(Register r1, Register r2, Register r3, Immediate imm);
void CMPfunc(Register r1, Register r2, Register r3, Immediate imm);
void ANDfunc(Register r1, Register r2, Register r3, Immediate imm);
void ORfunc(Register r1, Register r2, Register r3, Immediate imm);
void XORfunc(Register r1, Register r2, Register r3, Immediate imm);
void NOTfunc(Register r1, Register r2, Register r3, Immediate imm);
void LSLfunc(Register r1, Register r2, Register r3, Immediate imm);
void LSRfunc(Register r1, Register r2, Register r3, Immediate imm);
void ASRfunc(Register r1, Register r2, Register r3, Immediate imm);
void LSLIfunc(Register r1, Register r2, Register r3, Immediate imm);
void LSRIfunc(Register r1, Register r2, Register r3, Immediate imm);
void JMPfunc(Register r1, Register r2, Register r3, Immediate imm);
void CALLfunc(Register r1, Register r2, Register r3, Immediate imm);
void JEQfunc(Register r1, Register r2, Register r3, Immediate imm);
void JEQLfunc(Register r1, Register r2, Register r3, Immediate imm);
void JNEfunc(Register r1, Register r2, Register r3, Immediate imm);
void JNELfunc(Register r1, Register r2, Register r3, Immediate imm);
void JLTfunc(Register r1, Register r2, Register r3, Immediate imm);
void JLTLfunc(Register r1, Register r2, Register r3, Immediate imm);
void JLEfunc(Register r1, Register r2, Register r3, Immediate imm);
void JLELfunc(Register r1, Register r2, Register r3, Immediate imm);
void JGTfunc(Register r1, Register r2, Register r3, Immediate imm);
void JGTLfunc(Register r1, Register r2, Register r3, Immediate imm);
void JGEfunc(Register r1, Register r2, Register r3, Immediate imm);
void JGELfunc(Register r1, Register r2, Register r3, Immediate imm);
void DOTfunc(Register r1, Register r2, Register r3, Immediate imm);
void DMAfunc(Register r1, Register r2, Register r3, Immediate imm);
void CLIPfunc(Register r1, Register r2, Register r3, Immediate imm);
void CLSfunc(Register r1, Register r2, Register r3, Immediate imm);
void TREECLRfunc(Register r1, Register r2, Register r3, Immediate imm);
void TREEINfunc(Register r1, Register r2, Register r3, Immediate imm);
void TREESETfunc(Register r1, Register r2, Register r3, Immediate imm);
void TREEVALfunc(Register r1, Register r2, Register r3, Immediate imm);
void TREEPUTfunc(Register r1, Register r2, Register r3, Immediate imm);
void DecodeInstruction(Word inst, Opcode *op, Register *r1,
		       Register *r2, Register *r3, Immediate *imm);

extern OpFunction opTable[];
extern int numOps;
