    /* Register Loading and Storing */
    { "LD", "RA" },
    { "ST", "AR" },
    { "LI", "RA" },
    /* General Purpose Arithmetic and Logic */
    /*   Arithmetic */
    { "ADD", "RRR" },
    { "SUB", "RRR" },
    { "MUL", "RRR" },
    { "MULF", "RRR" },
    { "RECP", "RR" },
    /*   Logic and Bitwise */
    { "AND", "RRR" },
    { "OR", "RRR" },
    { "XOR", "RRR" },
    { "NOT", "RR" },
    { "LSL", "RRR" },
    { "LSR", "RRR" },
    { "ASR", "RRR" },
    { "LSLI", "RRI" },
    { "LSRI", "RRI" },
    { "ASRI", "RRI" },
    /* Control Flow */
    { "JMP", "A" },
    { "CALL", "A" },
    { "JEQ", "A" },
    { "JEQL", "A" },
    { "JNE", "A" },
    { "JNEL", "A" },
    { "JLT", "A" },
    { "JLTL", "A" },
    { "JLE", "A" },
    { "JLEL", "A" },
    { "JGT", "A" },
    { "JGTL", "A" },
    { "JGE", "A" },
    { "JGEL", "A" },
    /* Special Purpose Arithmetic */
    { "DOT", "RRR" },
    /* Direct Memory Access to External RAM */
    { "READ", "RR" },
    { "WRITE", "RR" },
    /* Rasterization */
    { "SCRSET", "RRI" },
    { "CLS", "RR" },
    { "TREESET", "RRR" },
    { "TREEIN", "RR" },
    { "TREEVAL", "RRI" },
    { "TREEPUT", "OP" },
