    /* Register Loading and Storing */
    LDfunc,
    STfunc,
    LIfunc,
    /* General Purpose Arithmetic and Logic */
    /*   Arithmetic */
    ADDfunc,
    SUBfunc,
    MULfunc,
    MULFfunc,
    RECPfunc,
    /*   Logic and Bitwise */
    ANDfunc,
    ORfunc,
    XORfunc,
    NOTfunc,
    LSLfunc,
    LSRfunc,
    ASRfunc,
    LSLIfunc,
    LSRIfunc,
    ASRIfunc,
    /* Control Flow */
    JMPfunc,
    CALLfunc,
    JEQfunc,
    JEQLfunc,
    JNEfunc,
    JNELfunc,
    JLTfunc,
    JLTLfunc,
    JLEfunc,
    JLELfunc,
    JGTfunc,
    JGTLfunc,
    JGEfunc,
    JGELfunc,
    /* Special Purpose Arithmetic */
    DOTfunc,
    /* Direct Memory Access to External RAM */
    READfunc,
    WRITEfunc,
    /* Rasterization */
    SCRSETfunc,
    CLSfunc,
    TREESETfunc,
    TREEINfunc,
    TREEVALfunc,
    TREEPUTfunc,
